POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "test3",
  "email": "test@gmail.com",
  "password": "asdasd",
  "name": "jhon doe"
}

####
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "test3",
  "password": "asdasd"
}

####
POST http://localhost:5000/api/auth/logout
Content-Type: application/json

####
GET http://localhost:5000/api/posts
Content-Type: application/json

###
POST http://localhost:5000/api/posts
Content-Type: application/json

{
"descrp": "hahaha"
}

####
GET http://localhost:5000/api/comments
Content-Type: application/json

####
GET http://localhost:5000/api/likes
Content-Type: application/json

####
GET http://localhost:5000/api//relationships?followedUserId=7
Content-Type: application/json

